weaponlist = {
    # Name : [stat, damage]
    "Club": ["STR", "1d4"],
    "Dagger": ["VERS", "1d4"],
    "Greatclub": ["STR", "1d8"],
    "Handaxe": ["STR", "1d6"],
    "Javelin": ["STR", "1d6"],
    "Mace": ["STR", "1d6"],
    "Quarterstaff": ["STR", "1d8"],
    "Sickle": ["STR", "1d6"],
    "Light Crossbow": ["DEX", "1d8"],
    "Darts": ["DEX", "1d4"],
    "Shortbow": ["DEX", "1d6"],
    "Sling": ["DEX", "1d4"],
    "Battleaxe": ["STR", "1d10"],
    "Flail": ["STR", "1d8"],
    "Glaive": ["STR", "1d10"],
    "Greataxe": ["STR", "1d12"],
    "Greatsword": ["STR", "2d6"],
    "Halberd": ["STR", "1d10"],
    "Lance": ["STR", "1d12"],
    "Longsword": ["VERS", "1d10"],
    "Maul": ["STR", "2d6"],
    "Morningstar": ["STR", "1d8"],
    "Pike": ["STR", "1d10"],
    "Rapier": ["VERS", "1d8"],
    "Scimitar": ["VERS", "1d6"],
    "Shortsword": ["VERS", "1d6"],
    "Trident": ["STR", "1d6"],
    "Warpick": ["STR", "1d8"],
    "Warhammer": ["STR", "1d10"],
    "Whip": ["STR", "1d4"],
    "Unarmed": ["DEX", "1d4"]
}