
class CharClass:
    def __init__(self, title, hit_die, saving_throws, skill_count, skill_profs, tool_profs,
                 weapon_profs, armor_profs, stat_recs, weapons, armor, equipment, features):
        self.title = title
        self.hit_die = hit_die
        self.saving_throws = saving_throws
        self.skill_count = skill_count
        self.skill_profs = skill_profs
        self.tool_profs = tool_profs
        self.weapon_profs = weapon_profs
        self.armor_profs = armor_profs
        self.stat_recs = stat_recs
        self.weapons = weapons
        self.armor = armor
        self.equipment = equipment
        self.features = features

ClassList = {
    'Artificer': CharClass('Artificer',
                           8,
                           ['CON', 'INT'],
                           2,
                           ['Arcana', 'History', 'Investigation', 'Medicine', 'Perception ', 'Sleight of Hand'],
                           ["Thieves' Tools", "Tinker's Tools", "One type of artisan's tools of your choice"],
                           ['Simple Weapons'],
                           ['Light Armor', 'Medium Armor', 'Shields'],
                           [8,12,14,15,13,10],
                           ["Dagger", "Light Crossbow"],
                           ["Studded Leather Armor"],
                           {"Thieves tools": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Barbarian': CharClass('Barbarian',
                           12,
                           ['CON', 'STR'],
                           2,
                           ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception ', 'Survival'],
                           [],
                           ['Simple Weapons', 'Martial Weapons'],
                           ['Light Armor', 'Medium Armor', 'Shields'],
                           [15,13,14,8,10,12],
                           ["Greataxe", "Handaxe", "Javelin"],
                           [],
                           {"Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Bard': CharClass('Bard',
                           8,
                           ['DEX', 'CHA'],
                           3,
                           ['Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception ', 'History', 'Insight',
                                'Intimidation', 'Investigation', 'Medicine', 'Nature', 'Perception ', 'Performance',
                                'Persuasion', 'Religion', 'Sleight of Hand', 'Stealth ', 'Survival'],
                           ['Musical Instrument', 'Musical Instrument', 'Musical Instrument'],
                           ['Simple Weapons', 'Hand Crossbows', 'Longsword', 'Rapier', 'Shortsword'],
                           ['Light Armor'],
                           [8,14,13,12,10,15],
                           ["Rapier", "Dagger"],
                           ["Leather Armor"],
                           {"Lute": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50} ,
                           []
    ),
    'Cleric': CharClass('Cleric',
                           8,
                           ['WIS', 'CHA'],
                           2,
                           ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'],
                           [],
                           ['Simple Weapons'],
                           ['Light Armor', 'Medium Armor', 'Shields'],
                           [13,8,14,10,15,12],
                           ["Warhammer", "Light Crossbow"],
                           ["Scale Mail", "Shield"],
                           {"Shield":1, "Holy Symbol":1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50} ,
                           []
    ),
    'Druid': CharClass('Druid',
                           8,
                           ['WIS', 'INT'],
                           2,
                           ['Arcana', 'Animal Handling', 'Insight', 'Medicine', 'Nature', 'Perception ', 'Religion','Survival'],
                           ['Herbalism kit'],
                           ['Club', 'Dagger', 'Darts', 'Javelins', 'Maces', 'Quarterstaff', 'Scimitars', 'Sickles','Slings', 'Spears'],
                           ['Light Armor', 'Medium Armor', 'Shields', 'No armor or shields made of metal'],
                           [8,13,14,10,15,12],
                           ["Scimitar"],
                           ["Leather Armor", "Shield"],
                           {"Druidic Focus": 1, "Shield":1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50} ,
                           []
    ),
    'Fighter': CharClass('Fighter',
                           10,
                           ['CON', 'STR'],
                           2,
                           ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation','Perception ', 'Survival'],
                           [],
                           ['Simple Weapons', 'Martial Weapons'],
                           ['All Armor', 'Shields'],
                           [15,13,14,12,10,8],
                           ["Longsword", "Handaxe", "Light Crossbow"],
                           ["Chain Mail", "Shield"],
                           {"Shield":1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50} ,
                           []
    ),
    'Monk': CharClass('Monk',
                           8,
                           ['DEX', 'STR'],
                           2,
                           ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation','Perception ', 'Survival'],
                           ["One type of Artisan's tools or one musical instrument"],
                           ['Simple Weapons', 'Shortsword'],
                           [],
                           [8,15,13,10,14,12],
                           ["Unarmed", "Shortsword", "Darts"],
                           [],
                           {"Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Paladin': CharClass('Paladin',
                           10,
                           ['CHA', 'WIS'],
                           2,
                           ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'],
                           [],
                           ['Simple Weapons', 'Martial Weapons'],
                           ['All armor', 'Shields'],
                           [15,8,13,10,12,14],
                           ["Greatsword", "Javelin"],
                           ["Chain Mail"],
                           {"Holy Symbol": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Ranger': CharClass('Ranger',
                           10,
                           ['DEX', 'STR'],
                           3,
                           ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception ', 'Stealth ', 'Survival'],
                           [],
                           ['Simple Weapons', 'Martial Weapons'],
                           ['Light Armor', 'Medium Armor', 'Shields'],
                           [10,15,13,8,14,12],
                           ["Shortsword", "Longbow"],
                           ["Scale Mail"],
                           {"Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Rogue': CharClass('Rogue',
                           8,
                           ['DEX', 'INT'],
                           4,
                           ['Acrobatics', 'Deception ', 'Insight', 'Intimidation', 'Investigation', 'Perception ', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth '],
                           ["Thieves' Tools"],
                           ['Simple Weapons', 'Hand Crossbows', 'Longswords', 'Rapiers', 'Shortswords'],
                           ['Light Armor'],
                           [8,15,12,14,10,13],
                           ["Rapier", "Dagger", "Shortbow"],
                           ["Leather Armor"],
                           {"Thieves tools": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Sorcerer': CharClass('Sorcerer',
                           6,
                           ['CON', 'CHA'],
                           2,
                           ['Arcana', 'Deception ', 'Insight', 'Intimidation', 'Persuasion', 'Religion'],
                           [],
                           ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light Crossbows'],
                           [],
                           [8,13,14,10,12,15],
                           ["Light Crossbow", "Dagger"],
                           [],
                           {"Arcane Focus": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Warlock': CharClass('Warlock',
                           8,
                           ['WIS', 'CHA'],
                           2,
                           ['Arcana', 'Deception ', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'],
                           [],
                           ['Simple Weapons'],
                           ['Light Armor'],
                           [10, 12,14,13,8,15],
                           ["Light Crossbow", "Dagger"],
                           ["Leather Armor"],
                           {"Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),
    'Wizard': CharClass('Wizard',
                           6,
                           ['WIS', 'INT'],
                           2,
                           ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'],
                           [],
                           ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light Crossbows'],
                           [],
                           [8,14,13,15,10,12],
                           ["Dagger"],
                           [],
                           {"Arcane Focus": 1, "Spellbook": 1, "Backpack": 1, "Crowbar": 1, "Hammer": 1, "Pitons": 10, "Torches": 10, "Tinderbox": 1, "Waterskin": 1, "Hemp Rope": 50},
                           []
    ),

    }
